// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VillaMon_API.Data;

#nullable disable

namespace VillaMon_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240831151422_UpdateBookingVilla")]
    partial class UpdateBookingVilla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VillaMon_API.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuestCount")
                        .HasColumnType("int");

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("VillaId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            BookingId = 1,
                            CheckInDate = new DateTime(2024, 9, 10, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5237),
                            CheckOutDate = new DateTime(2024, 9, 15, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5242),
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5244),
                            GuestCount = 4,
                            GuestEmail = "john.doe@example.com",
                            GuestName = "John Doe",
                            PaymentStatus = "Paid",
                            UpdatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5245),
                            VillaId = 1
                        },
                        new
                        {
                            BookingId = 2,
                            CheckInDate = new DateTime(2024, 9, 20, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5247),
                            CheckOutDate = new DateTime(2024, 9, 25, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5248),
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5250),
                            GuestCount = 2,
                            GuestEmail = "jane.smith@example.com",
                            GuestName = "Jane Smith",
                            PaymentStatus = "Pending",
                            UpdatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5251),
                            VillaId = 2
                        },
                        new
                        {
                            BookingId = 3,
                            CheckInDate = new DateTime(2024, 9, 5, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5253),
                            CheckOutDate = new DateTime(2024, 9, 8, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5254),
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5256),
                            GuestCount = 3,
                            GuestEmail = "alice.johnson@example.com",
                            GuestName = "Alice Johnson",
                            PaymentStatus = "Cancelled",
                            UpdatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5257),
                            VillaId = 3
                        },
                        new
                        {
                            BookingId = 4,
                            CheckInDate = new DateTime(2024, 9, 12, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5258),
                            CheckOutDate = new DateTime(2024, 9, 17, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5260),
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5261),
                            GuestCount = 6,
                            GuestEmail = "michael.brown@example.com",
                            GuestName = "Michael Brown",
                            PaymentStatus = "Paid",
                            UpdatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5262),
                            VillaId = 4
                        },
                        new
                        {
                            BookingId = 5,
                            CheckInDate = new DateTime(2024, 9, 2, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5264),
                            CheckOutDate = new DateTime(2024, 9, 6, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5265),
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5267),
                            GuestCount = 8,
                            GuestEmail = "emily.davis@example.com",
                            GuestName = "Emily Davis",
                            PaymentStatus = "Paid",
                            UpdatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5268),
                            VillaId = 5
                        },
                        new
                        {
                            BookingId = 6,
                            CheckInDate = new DateTime(2024, 9, 11, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5270),
                            CheckOutDate = new DateTime(2024, 9, 16, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5271),
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5272),
                            GuestCount = 2,
                            GuestEmail = "david.wilson@example.com",
                            GuestName = "David Wilson",
                            PaymentStatus = "Pending",
                            UpdatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5273),
                            VillaId = 6
                        },
                        new
                        {
                            BookingId = 7,
                            CheckInDate = new DateTime(2024, 9, 1, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5275),
                            CheckOutDate = new DateTime(2024, 9, 4, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5276),
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5278),
                            GuestCount = 4,
                            GuestEmail = "sarah.miller@example.com",
                            GuestName = "Sarah Miller",
                            PaymentStatus = "Paid",
                            UpdatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5279),
                            VillaId = 7
                        },
                        new
                        {
                            BookingId = 8,
                            CheckInDate = new DateTime(2024, 9, 3, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5280),
                            CheckOutDate = new DateTime(2024, 9, 9, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5281),
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5283),
                            GuestCount = 3,
                            GuestEmail = "jessica.white@example.com",
                            GuestName = "Jessica White",
                            PaymentStatus = "Pending",
                            UpdatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5284),
                            VillaId = 8
                        },
                        new
                        {
                            BookingId = 9,
                            CheckInDate = new DateTime(2024, 9, 14, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5285),
                            CheckOutDate = new DateTime(2024, 9, 18, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5287),
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5288),
                            GuestCount = 2,
                            GuestEmail = "steven.harris@example.com",
                            GuestName = "Steven Harris",
                            PaymentStatus = "Cancelled",
                            UpdatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5289),
                            VillaId = 9
                        },
                        new
                        {
                            BookingId = 10,
                            CheckInDate = new DateTime(2024, 9, 7, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5291),
                            CheckOutDate = new DateTime(2024, 9, 13, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5292),
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5293),
                            GuestCount = 1,
                            GuestEmail = "anna.martin@example.com",
                            GuestName = "Anna Martin",
                            PaymentStatus = "Paid",
                            UpdatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5294),
                            VillaId = 10
                        },
                        new
                        {
                            BookingId = 11,
                            CheckInDate = new DateTime(2024, 9, 22, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5296),
                            CheckOutDate = new DateTime(2024, 9, 27, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5297),
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5299),
                            GuestCount = 5,
                            GuestEmail = "paul.thompson@example.com",
                            GuestName = "Paul Thompson",
                            PaymentStatus = "Paid",
                            UpdatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5300),
                            VillaId = 11
                        },
                        new
                        {
                            BookingId = 12,
                            CheckInDate = new DateTime(2024, 9, 16, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5301),
                            CheckOutDate = new DateTime(2024, 9, 19, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5302),
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5304),
                            GuestCount = 2,
                            GuestEmail = "olivia.lewis@example.com",
                            GuestName = "Olivia Lewis",
                            PaymentStatus = "Pending",
                            UpdatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5305),
                            VillaId = 12
                        },
                        new
                        {
                            BookingId = 13,
                            CheckInDate = new DateTime(2024, 9, 8, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5307),
                            CheckOutDate = new DateTime(2024, 9, 10, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5308),
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5309),
                            GuestCount = 3,
                            GuestEmail = "isabella.clark@example.com",
                            GuestName = "Isabella Clark",
                            PaymentStatus = "Paid",
                            UpdatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5310),
                            VillaId = 13
                        },
                        new
                        {
                            BookingId = 14,
                            CheckInDate = new DateTime(2024, 9, 4, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5312),
                            CheckOutDate = new DateTime(2024, 9, 9, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5313),
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5314),
                            GuestCount = 4,
                            GuestEmail = "daniel.walker@example.com",
                            GuestName = "Daniel Walker",
                            PaymentStatus = "Cancelled",
                            UpdatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5315),
                            VillaId = 14
                        },
                        new
                        {
                            BookingId = 15,
                            CheckInDate = new DateTime(2024, 9, 2, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5317),
                            CheckOutDate = new DateTime(2024, 9, 5, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5318),
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5320),
                            GuestCount = 6,
                            GuestEmail = "ethan.hall@example.com",
                            GuestName = "Ethan Hall",
                            PaymentStatus = "Paid",
                            UpdatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5321),
                            VillaId = 15
                        },
                        new
                        {
                            BookingId = 16,
                            CheckInDate = new DateTime(2024, 9, 10, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5322),
                            CheckOutDate = new DateTime(2024, 9, 14, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5323),
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5325),
                            GuestCount = 2,
                            GuestEmail = "sophia.allen@example.com",
                            GuestName = "Sophia Allen",
                            PaymentStatus = "Pending",
                            UpdatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5326),
                            VillaId = 16
                        },
                        new
                        {
                            BookingId = 17,
                            CheckInDate = new DateTime(2024, 9, 5, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5328),
                            CheckOutDate = new DateTime(2024, 9, 7, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5329),
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5330),
                            GuestCount = 8,
                            GuestEmail = "matthew.young@example.com",
                            GuestName = "Matthew Young",
                            PaymentStatus = "Paid",
                            UpdatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5331),
                            VillaId = 17
                        },
                        new
                        {
                            BookingId = 18,
                            CheckInDate = new DateTime(2024, 9, 9, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5333),
                            CheckOutDate = new DateTime(2024, 9, 11, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5334),
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5335),
                            GuestCount = 1,
                            GuestEmail = "chloe.king@example.com",
                            GuestName = "Chloe King",
                            PaymentStatus = "Pending",
                            UpdatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5336),
                            VillaId = 18
                        },
                        new
                        {
                            BookingId = 19,
                            CheckInDate = new DateTime(2024, 9, 6, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5338),
                            CheckOutDate = new DateTime(2024, 9, 8, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5339),
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5341),
                            GuestCount = 3,
                            GuestEmail = "grace.scott@example.com",
                            GuestName = "Grace Scott",
                            PaymentStatus = "Cancelled",
                            UpdatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5342),
                            VillaId = 19
                        },
                        new
                        {
                            BookingId = 20,
                            CheckInDate = new DateTime(2024, 9, 12, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5343),
                            CheckOutDate = new DateTime(2024, 9, 15, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5344),
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5346),
                            GuestCount = 5,
                            GuestEmail = "benjamin.turner@example.com",
                            GuestName = "Benjamin Turner",
                            PaymentStatus = "Paid",
                            UpdatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5347),
                            VillaId = 20
                        });
                });

            modelBuilder.Entity("VillaMon_API.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "Private Pool, Garden, Spa, Gym",
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5011),
                            Details = "A luxurious villa with royal amenities, including a private pool, garden, and a spacious living area.",
                            ImageUrl = "https://dotnetmastery.com/bluevillaimages/villa3.jpg",
                            IsAvailable = true,
                            Location = "Downtown City Center",
                            Name = "Royal Villa",
                            Occupancy = 6,
                            Rate = 350.0,
                            Sqft = 850,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Infinity Pool, Ocean View, BBQ Area",
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5061),
                            Details = "An exclusive villa near the beach, featuring an infinity pool and breathtaking sea views.",
                            ImageUrl = "https://dotnetmastery.com/bluevillaimages/villa1.jpg",
                            IsAvailable = false,
                            Location = "Seaside",
                            Name = "Premium Pool Villa",
                            Occupancy = 4,
                            Rate = 450.0,
                            Sqft = 700,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "Private Pool, Rooftop Terrace, Modern Kitchen",
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5065),
                            Details = "A stunning villa with a private pool, state-of-the-art kitchen, and a rooftop terrace.",
                            ImageUrl = "https://dotnetmastery.com/bluevillaimages/villa4.jpg",
                            IsAvailable = true,
                            Location = "Hilltop",
                            Name = "Luxury Pool Villa",
                            Occupancy = 5,
                            Rate = 500.0,
                            Sqft = 950,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "Mountain View, Fireplace, Wine Cellar",
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5068),
                            Details = "An exquisite villa with crystal-clear views of the mountains, perfect for those seeking tranquility.",
                            ImageUrl = "https://dotnetmastery.com/bluevillaimages/villa5.jpg",
                            IsAvailable = true,
                            Location = "Mountain View",
                            Name = "Diamond Villa",
                            Occupancy = 8,
                            Rate = 600.0,
                            Sqft = 1200,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "Grand Pool, Large Courtyard, Outdoor Kitchen",
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5070),
                            Details = "A villa with a grand pool and a large courtyard, ideal for large families or groups.",
                            ImageUrl = "https://dotnetmastery.com/bluevillaimages/villa2.jpg",
                            IsAvailable = false,
                            Location = "Countryside",
                            Name = "Diamond Pool Villa",
                            Occupancy = 10,
                            Rate = 700.0,
                            Sqft = 1500,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Amenity = "Solar Panels, Rainwater Harvesting, Eco-friendly Appliances",
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5073),
                            Details = "A sustainable villa with solar panels and a rainwater harvesting system.",
                            ImageUrl = "https://dotnetmastery.com/bluevillaimages/villa6.jpg",
                            IsAvailable = true,
                            Location = "Forest Edge",
                            Name = "Eco Villa",
                            Occupancy = 4,
                            Rate = 300.0,
                            Sqft = 600,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Amenity = "Beach Access, Sun Deck, Sea Kayak",
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5075),
                            Details = "A beachfront villa with direct access to the sandy shores.",
                            ImageUrl = "https://dotnetmastery.com/bluevillaimages/villa7.jpg",
                            IsAvailable = true,
                            Location = "Beachfront",
                            Name = "Beachfront Villa",
                            Occupancy = 6,
                            Rate = 800.0,
                            Sqft = 900,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Amenity = "Modern Decor, High Ceilings, Open Floor Plan",
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5077),
                            Details = "A stylish loft with modern decor and high ceilings.",
                            ImageUrl = "https://dotnetmastery.com/bluevillaimages/villa8.jpg",
                            IsAvailable = false,
                            Location = "Urban Area",
                            Name = "Modern Loft Villa",
                            Occupancy = 3,
                            Rate = 400.0,
                            Sqft = 500,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Amenity = "Treehouse, Rope Bridge, Nature Walks",
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5080),
                            Details = "An adventurous villa built atop a tall tree with stunning views.",
                            ImageUrl = "https://dotnetmastery.com/bluevillaimages/villa9.jpg",
                            IsAvailable = true,
                            Location = "Forest Canopy",
                            Name = "Treehouse Villa",
                            Occupancy = 2,
                            Rate = 550.0,
                            Sqft = 300,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Amenity = "Cave Rooms, Natural Pools, Unique Experience",
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5082),
                            Details = "A unique villa built into the rock formations of a cave.",
                            ImageUrl = "https://dotnetmastery.com/bluevillaimages/villa10.jpg",
                            IsAvailable = false,
                            Location = "Mountain Cave",
                            Name = "Cave Villa",
                            Occupancy = 4,
                            Rate = 600.0,
                            Sqft = 750,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Amenity = "Panoramic Views, Rooftop Pool, Private Elevator",
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5085),
                            Details = "A luxurious penthouse with panoramic city views.",
                            ImageUrl = "https://dotnetmastery.com/bluevillaimages/villa11.jpg",
                            IsAvailable = true,
                            Location = "City Center",
                            Name = "Skyline Penthouse Villa",
                            Occupancy = 4,
                            Rate = 1000.0,
                            Sqft = 1400,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Amenity = "Fireplaces, Hot Tubs, Mountain View",
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5088),
                            Details = "A cozy chalet with fireplaces and hot tubs.",
                            ImageUrl = "https://dotnetmastery.com/bluevillaimages/villa12.jpg",
                            IsAvailable = false,
                            Location = "Mountain Peak",
                            Name = "Mountain Chalet Villa",
                            Occupancy = 6,
                            Rate = 750.0,
                            Sqft = 1100,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Amenity = "Ocean Views, Water Deck, Swimming Access",
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5091),
                            Details = "A villa built on stilts over water, offering tranquility and ocean views.",
                            ImageUrl = "https://dotnetmastery.com/bluevillaimages/villa13.jpg",
                            IsAvailable = true,
                            Location = "Overwater",
                            Name = "Water Villa",
                            Occupancy = 5,
                            Rate = 900.0,
                            Sqft = 850,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Amenity = "Desert Views, Private Patios, Stargazing Deck",
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5093),
                            Details = "A secluded villa in the desert with unique architecture.",
                            ImageUrl = "https://dotnetmastery.com/bluevillaimages/villa14.jpg",
                            IsAvailable = false,
                            Location = "Desert",
                            Name = "Desert Retreat Villa",
                            Occupancy = 2,
                            Rate = 500.0,
                            Sqft = 650,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Amenity = "Wood Stove, Nature Trails, Wildlife Viewing",
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5095),
                            Details = "A quaint cabin in the forest for a nature getaway.",
                            ImageUrl = "https://dotnetmastery.com/bluevillaimages/villa15.jpg",
                            IsAvailable = true,
                            Location = "Forest",
                            Name = "Forest Cabin Villa",
                            Occupancy = 3,
                            Rate = 350.0,
                            Sqft = 400,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Amenity = "Ocean Views, Infinity Pool, Outdoor Fireplace",
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5098),
                            Details = "A villa perched on the edge of a cliff with breathtaking ocean views.",
                            ImageUrl = "https://dotnetmastery.com/bluevillaimages/villa16.jpg",
                            IsAvailable = true,
                            Location = "Cliffside",
                            Name = "Cliffside Villa",
                            Occupancy = 4,
                            Rate = 1100.0,
                            Sqft = 900,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Amenity = "Private Island, Beach Access, Helicopter Pad",
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5100),
                            Details = "A private villa located on its own island, providing total seclusion.",
                            ImageUrl = "https://dotnetmastery.com/bluevillaimages/villa17.jpg",
                            IsAvailable = false,
                            Location = "Private Island",
                            Name = "Island Villa",
                            Occupancy = 8,
                            Rate = 1500.0,
                            Sqft = 2000,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Amenity = "Garden, Farmhouse Kitchen, Fireplace",
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5102),
                            Details = "A charming cottage with a beautiful garden in the countryside.",
                            ImageUrl = "https://dotnetmastery.com/bluevillaimages/villa18.jpg",
                            IsAvailable = true,
                            Location = "Countryside",
                            Name = "Countryside Cottage Villa",
                            Occupancy = 5,
                            Rate = 300.0,
                            Sqft = 600,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            Amenity = "Fishing Dock, Hammock, Canoe",
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5104),
                            Details = "A serene villa by the river, perfect for fishing and relaxation.",
                            ImageUrl = "https://dotnetmastery.com/bluevillaimages/villa19.jpg",
                            IsAvailable = false,
                            Location = "Riverfront",
                            Name = "Riverfront Villa",
                            Occupancy = 3,
                            Rate = 400.0,
                            Sqft = 550,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            Amenity = "Safari Tours, Campfire Area, Wildlife Viewing",
                            CreatedDate = new DateTime(2024, 8, 31, 16, 14, 22, 181, DateTimeKind.Local).AddTicks(5107),
                            Details = "A safari-style villa in the heart of the jungle, with guided wildlife tours.",
                            ImageUrl = "https://dotnetmastery.com/bluevillaimages/villa20.jpg",
                            IsAvailable = true,
                            Location = "Jungle",
                            Name = "Jungle Safari Villa",
                            Occupancy = 4,
                            Rate = 700.0,
                            Sqft = 800,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("VillaMon_API.Models.Booking", b =>
                {
                    b.HasOne("VillaMon_API.Models.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
